/**
 * @file simulator/main.cpp
 * @brief QtLvglDesigner 仿真器命令行入口
 *
 * 用法：
 *   QtLvglSimu <lua_script_path> [--width <px>] [--height <px>] [--title <text>]
 *
 * 仿真器自身保持轻量：只负责解析命令行参数，
 * 真正的初始化（LVGL/SDL/Lua 绑定/主循环）由 LvglLuaBinding.dll 中的
 * lvgl_simulator_run() 完成。
 */

#include <QCoreApplication>
#include <QCommandLineParser>
#include <QFile>
#include <QFileInfo>
#include <QString>
#include <QByteArray>
#include <QDebug>

#include <cstdio>

#ifdef Q_OS_WIN
#  include <windows.h>
#endif

#include "lvgl_lua_bindings.h"

int main(int argc, char *argv[])
{
#ifdef Q_OS_WIN
    // 将控制台设置为 UTF-8 以支持中文输出
    SetConsoleCP(CP_UTF8);
    SetConsoleOutputCP(CP_UTF8);
#endif
    QCoreApplication app(argc, argv);
    QCoreApplication::setApplicationName(QStringLiteral("QtLvglSimu"));
    QCoreApplication::setApplicationVersion(QStringLiteral("1.0.0"));

    QCommandLineParser parser;
    parser.setApplicationDescription(
        QStringLiteral("QtLvglDesigner Simulator - run designer-generated Lua scripts"));
    parser.addHelpOption();
    parser.addVersionOption();
    parser.addPositionalArgument(
        QStringLiteral("script"),
        QStringLiteral("Lua entry script generated by the designer."));

    QCommandLineOption widthOpt(
        QStringList() << QStringLiteral("width"),
        QStringLiteral("Simulator window width in pixels (default: 800)."),
        QStringLiteral("px"), QStringLiteral("800"));
    QCommandLineOption heightOpt(
        QStringList() << QStringLiteral("height"),
        QStringLiteral("Simulator window height in pixels (default: 480)."),
        QStringLiteral("px"), QStringLiteral("480"));
    QCommandLineOption titleOpt(
        QStringList() << QStringLiteral("title"),
        QStringLiteral("Simulator window title."),
        QStringLiteral("text"), QStringLiteral("QtLvglSimu"));

    parser.addOption(widthOpt);
    parser.addOption(heightOpt);
    parser.addOption(titleOpt);

    parser.process(app);

    const QStringList positional = parser.positionalArguments();
    if (positional.isEmpty()) {
        qCritical().noquote() << QStringLiteral("Error: missing Lua script path.");
        parser.showHelp(1);
        return 1;
    }

    const QString scriptPath = positional.first();
    if (!QFileInfo::exists(scriptPath)) {
        qCritical().noquote()
            << QStringLiteral("Error: script not found: %1").arg(scriptPath);
        return 2;
    }

    bool okW = false, okH = false;
    int width  = parser.value(widthOpt).toInt(&okW);
    int height = parser.value(heightOpt).toInt(&okH);
    if (!okW || width  <= 0) width  = 800;
    if (!okH || height <= 0) height = 480;

    const QString title = parser.value(titleOpt);

    // 不写入 simulator.log：仿真日志仅通过 stdout/stderr 交给组态软件界面显示。
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    std::setvbuf(stderr, nullptr, _IONBF, 0);

    const QByteArray scriptUtf8 = QFile::encodeName(scriptPath);
    const QByteArray titleUtf8  = title.toUtf8();

    // 调用 LvglLuaBinding 中的仿真入口；正常关窗时 LVGL 内部会直接 exit(0)
    return lvgl_simulator_run(scriptUtf8.constData(),
                              width, height,
                              titleUtf8.constData());
}
