/**
 * @file simulator/main.cpp
 * @brief QtLvglDesigner 仿真器命令行入口
 *
 * 用法：
 *   QtLvglSimu <lua_script_path> [--width <px>] [--height <px>] [--title <text>]
 *
 * 仿真器自身保持轻量：只负责解析命令行参数，
 * 真正的初始化（LVGL/SDL/Lua 绑定/主循环）由 LvglLuaBinding.dll 中的
 * lvgl_simulator_run() 完成。
 */

#include <QCoreApplication>
#include <QCommandLineParser>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QString>
#include <QByteArray>
#include <QDebug>

#include <cstdio>

#ifdef Q_OS_WIN
#  include <windows.h>
#  include <io.h>
#  include <fcntl.h>
#endif

#include "lvgl_lua_bindings.h"

namespace {

/// 把 stdout/stderr 重定向到 <scriptDir>/simulator.log，
/// 让 LVGL/Lua/runtime 的诊断信息在没有控制台时也能落盘。
/// 同时尝试附着到父进程的控制台（若有）以便调试模式可见。
void setupSimulatorLogging(const QString &scriptPath)
{
#ifdef Q_OS_WIN
    // 优先尝试挂到父进程控制台（从命令行启动时可见）
    if (::AttachConsole(ATTACH_PARENT_PROCESS)) {
        FILE *f = nullptr;
        freopen_s(&f, "CONOUT$", "w", stdout);
        freopen_s(&f, "CONOUT$", "w", stderr);
        return;
    }
#endif
    const QString logPath =
        QFileInfo(scriptPath).absoluteDir().filePath(QStringLiteral("simulator.log"));
    const QByteArray logUtf8 = QFile::encodeName(logPath);

#ifdef Q_OS_WIN
    FILE *fout = nullptr;
    FILE *ferr = nullptr;
    freopen_s(&fout, logUtf8.constData(), "w", stdout);
    freopen_s(&ferr, logUtf8.constData(), "a", stderr);
#else
    std::freopen(logUtf8.constData(), "w", stdout);
    std::freopen(logUtf8.constData(), "a", stderr);
#endif
    // 尽快 flush，避免崩溃时丢失最后几行
    //if (fout) std::setvbuf(stdout, nullptr, _IOLBF, 0);
    //if (ferr) std::setvbuf(stderr, nullptr, _IONBF, 0);
}

} // namespace

int main(int argc, char *argv[])
{
#ifdef Q_OS_WIN
    // 将控制台设置为 UTF-8 以支持中文输出
    SetConsoleCP(CP_UTF8);
    SetConsoleOutputCP(CP_UTF8);
#endif
    QCoreApplication app(argc, argv);
    QCoreApplication::setApplicationName(QStringLiteral("QtLvglSimu"));
    QCoreApplication::setApplicationVersion(QStringLiteral("1.0.0"));

    QCommandLineParser parser;
    parser.setApplicationDescription(
        QStringLiteral("QtLvglDesigner Simulator - run designer-generated Lua scripts"));
    parser.addHelpOption();
    parser.addVersionOption();
    parser.addPositionalArgument(
        QStringLiteral("script"),
        QStringLiteral("Lua entry script generated by the designer."));

    QCommandLineOption widthOpt(
        QStringList() << QStringLiteral("width"),
        QStringLiteral("Simulator window width in pixels (default: 800)."),
        QStringLiteral("px"), QStringLiteral("800"));
    QCommandLineOption heightOpt(
        QStringList() << QStringLiteral("height"),
        QStringLiteral("Simulator window height in pixels (default: 480)."),
        QStringLiteral("px"), QStringLiteral("480"));
    QCommandLineOption titleOpt(
        QStringList() << QStringLiteral("title"),
        QStringLiteral("Simulator window title."),
        QStringLiteral("text"), QStringLiteral("QtLvglSimu"));

    parser.addOption(widthOpt);
    parser.addOption(heightOpt);
    parser.addOption(titleOpt);

    parser.process(app);

    const QStringList positional = parser.positionalArguments();
    if (positional.isEmpty()) {
        qCritical().noquote() << QStringLiteral("Error: missing Lua script path.");
        parser.showHelp(1);
        return 1;
    }

    const QString scriptPath = positional.first();
    if (!QFileInfo::exists(scriptPath)) {
        qCritical().noquote()
            << QStringLiteral("Error: script not found: %1").arg(scriptPath);
        return 2;
    }

    bool okW = false, okH = false;
    int width  = parser.value(widthOpt).toInt(&okW);
    int height = parser.value(heightOpt).toInt(&okH);
    if (!okW || width  <= 0) width  = 800;
    if (!okH || height <= 0) height = 480;

    const QString title = parser.value(titleOpt);

    // 在调用 lvgl_simulator_run 之前把日志通道接好
    //setupSimulatorLogging(scriptPath);
    //std::fprintf(stdout, "[simulator] script=%s size=%dx%d title=%s\n",
    //             scriptPath.toLocal8Bit().constData(),
    //             width, height,
    //             title.toLocal8Bit().constData());
    //std::fflush(stdout);

    const QByteArray scriptUtf8 = QFile::encodeName(scriptPath);
    const QByteArray titleUtf8  = title.toUtf8();

    // 调用 LvglLuaBinding 中的仿真入口；正常关窗时 LVGL 内部会直接 exit(0)
    return lvgl_simulator_run(scriptUtf8.constData(),
                              width, height,
                              titleUtf8.constData());
}
